// Extensions.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire

extension Bool: JSONEncodable {
    func encodeToJSON() -> AnyObject { return self as AnyObject }
}

extension Float: JSONEncodable {
    func encodeToJSON() -> AnyObject { return self as AnyObject }
}

extension Int: JSONEncodable {
    func encodeToJSON() -> AnyObject { return self as AnyObject }
}

extension Double: JSONEncodable {
    func encodeToJSON() -> AnyObject { return self as AnyObject }
}

extension String: JSONEncodable {
    func encodeToJSON() -> AnyObject { return self as AnyObject }
}

private func encodeIfPossible<T>(_ object: T) -> AnyObject {
    if object is JSONEncodable {
        return (object as! JSONEncodable).encodeToJSON()
    } else {
        return object as AnyObject
    }
}

extension Array: JSONEncodable {
    func encodeToJSON() -> AnyObject {
        return self.map(encodeIfPossible)
    }
}

extension Dictionary: JSONEncodable {
    func encodeToJSON() -> AnyObject {
        var dictionary = [NSObject:AnyObject]()
        for (key, value) in self {
            dictionary[key as! NSObject] = encodeIfPossible(value)
        }
        return dictionary as AnyObject
    }
}


private let dateFormatter: DateFormatter = {
    let dateFormatter = DateFormatter()
    dateFormatter.dateFormat = "yyyy-MM-dd"
    return dateFormatter
}()

extension NSDate: JSONEncodable {
    func encodeToJSON() -> AnyObject {
        return dateFormatter.string(from: self as Date) as (Date) as (Date)
    }
}


