//
// Home.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Home: JSONEncodable {

    /** Unique identifier */
    open var home_id: Double?
    /** Humidity of home. */
    open var humidity: Double?
    /** Temperature of home. */
    open var temperature: Double?
    /** Noise of home. */
    open var sound: Double?
    /** Vibration of home. */
    open var vibration: Double?
    /** Dust of home. */
    open var dust: Double?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["home_id"] = self.home_id as AnyObject
        nillableDictionary["humidity"] = self.humidity as AnyObject
        nillableDictionary["temperature"] = self.temperature as AnyObject
        nillableDictionary["sound"] = self.sound as AnyObject
        nillableDictionary["vibration"] = self.vibration as AnyObject
        nillableDictionary["dust"] = self.dust as AnyObject
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary as AnyObject
    }
}
