//
// Home.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Home: JSONEncodable {

    /** Unique identifier */
    public var home_id: Double?
    /** Humidity of home. */
    public var humidity: Double?
    /** Temperature of home. */
    public var temperature: Double?
    /** Noise of home. */
    public var sound: Double?
    /** Vibration of home. */
    public var vibration: Double?
    /** Dust of home. */
    public var dust: Double?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["home_id"] = self.home_id
        nillableDictionary["humidity"] = self.humidity
        nillableDictionary["temperature"] = self.temperature
        nillableDictionary["sound"] = self.sound
        nillableDictionary["vibration"] = self.vibration
        nillableDictionary["dust"] = self.dust
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
