platform :ios, '9.0'
use_frameworks!

xcodeproj 'Algol/Algol.xcodeproj'

def testing_pods
  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', '3.0.0'
end

target 'Algol' do
  pod 'TaskQueue', '~> 0.9.8'
  pod 'Alamofire', '~> 3.0'
  pod 'Argo', '~> 2.2.0'
end

target 'AlgolTests' do
  testing_pods
end

target 'AlgolUITests' do
  testing_pods
end