platform :ios, '8.0'
use_frameworks!
xcodeproj 'Algol.xcodeproj'

def testing_pods
    pod 'Quick', '~> 0.8.0'
    pod 'Nimble', '3.0.0'
end

target 'Algol' do
    pod 'RxSwift', '~> 2.0.0-beta.2'
    pod 'Alamofire', '~> 3.0'
    pod 'Argo', '~> 2.2.0'
    pod 'Curry', '~> 1.4.0'
    pod 'PixateFreestyle'
    pod 'SwiftDate'
end

target 'AlgolWidget' do
    pod 'RxSwift', '~> 2.0.0-beta.2'
end

target 'AlgolTests' do
    testing_pods
end

target 'AlgolUITests' do
    testing_pods
end
