platform :ios, '8.0'
use_frameworks!
xcodeproj 'Algol.xcodeproj'

target 'Algol' do
  pod 'RxSwift', '~> 2.0.0-beta.2'
  pod 'TaskQueue', '~> 0.9.8'
  pod 'Alamofire', '~> 3.0'
  pod 'Argo', '~> 2.2.0'
  pod 'Curry', '~> 1.4.0'
end